version: '3'

services:
  backend:
    image: "supercar031/supercar:backend"
    container_name: supercar-backend
    build:
      context: .
    restart: always
    ports:
      - '9999:80'
    env_file:
      - dev.env